FUNCTION GETFF(RS)

  USE CONSTANTS; USE STORAGE; IMPLICIT NONE
  REAL(KIND = PREC), INTENT(IN) :: RS
  REAL(KIND = PREC) :: GETFF
  INTEGER :: LOC 

  LOC = FLOOR((INITIAL_REDSHIFT - RS) / ABS(DZ)) + 1
  IF (LOC < 1) THEN
     GETFF = 0.0_PREC
  ELSE
     GETFF = FFARR(LOC)
  END IF

END FUNCTION GETFF
